 CREATE DATABASE notizy_404;

 USE notizy_404;

 CREATE TABLE user (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

 CREATE TABLE notizen (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (Username) REFERENCES user(username) ON DELETE CASCADE ON UPDATE CASCADE,
    Titel VARCHAR(255) NOT NULL,
    Inhalt varchar (500) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 );
